databases:
  - name: realtime_searchbox_helpjuice
    databaseName: realtime_searchbox_development
    user: realtime_searchbox_user

services:
  - type: web
    name: realtime_searchbox_helpjuice
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realtime_searchbox_helpjuice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
